// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLoginQRCode(arg1) {
  return window['go']['main']['AppBridge']['GetLoginQRCode'](arg1);
}

export function GetLoginStatus(arg1) {
  return window['go']['main']['AppBridge']['GetLoginStatus'](arg1);
}

export function GetOverview() {
  return window['go']['main']['AppBridge']['GetOverview']();
}

export function ListEvents(arg1, arg2) {
  return window['go']['main']['AppBridge']['ListEvents'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['AppBridge']['Logout'](arg1);
}

export function NowBJ() {
  return window['go']['main']['AppBridge']['NowBJ']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['main']['AppBridge']['SaveSettings'](arg1, arg2);
}

export function SendText(arg1, arg2, arg3) {
  return window['go']['main']['AppBridge']['SendText'](arg1, arg2, arg3);
}

export function StartLogin() {
  return window['go']['main']['AppBridge']['StartLogin']();
}
