// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function GetLoginQRCode(arg1:string):Promise<string>;

export function GetLoginStatus(arg1:string):Promise<main.LoginSessionView>;

export function GetOverview():Promise<main.Overview>;

export function ListEvents(arg1:number,arg2:number):Promise<Array<main.EventView>>;

export function Logout(arg1:string):Promise<void>;

export function NowBJ():Promise<string>;

export function SaveSettings(arg1:string,arg2:string):Promise<model.Settings>;

export function SendText(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartLogin():Promise<main.LoginSessionView>;
